# Generated by Django 3.2.5 on 2021-08-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.CharField(default='https://picsum.photos/600', max_length=200),
        ),
    ]
