# Generated by Django 3.2.5 on 2021-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='https://picsum.photos/600'),
        ),
    ]
