# Generated by Django 3.2.5 on 2021-08-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='image',
            new_name='image_url',
        ),
    ]
